# modified from https://github.com/argenos/nldates-obsidian/blob/master/.github/workflows/release.yml
# which is released under MIT License

# trigger:
# modify manifest.json, package.json, versions.json
# git tag <version number>
# git push origin --tags

name: Release A New Version

on:
  push:
    branches:
      - master
    paths:
      - 'manifest.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    environment: env-for-buildci

    env:
      DROPBOX_APP_KEY: ${{secrets.DROPBOX_APP_KEY}}
      ONEDRIVE_CLIENT_ID: ${{secrets.ONEDRIVE_CLIENT_ID}}
      ONEDRIVE_AUTHORITY: ${{secrets.ONEDRIVE_AUTHORITY}}
      REMOTELYSAVE_WEBSITE: ${{secrets.REMOTELYSAVE_WEBSITE}}
      REMOTELYSAVE_CLIENT_ID: ${{secrets.REMOTELYSAVE_CLIENT_ID}}
      GOOGLEDRIVE_CLIENT_ID: ${{secrets.GOOGLEDRIVE_CLIENT_ID}}
      GOOGLEDRIVE_CLIENT_SECRET: ${{secrets.GOOGLEDRIVE_CLIENT_SECRET}}
      BOX_CLIENT_ID: ${{secrets.BOX_CLIENT_ID}}
      BOX_CLIENT_SECRET: ${{secrets.BOX_CLIENT_SECRET}}
      PCLOUD_CLIENT_ID: ${{secrets.PCLOUD_CLIENT_ID}}
      PCLOUD_CLIENT_SECRET: ${{secrets.PCLOUD_CLIENT_SECRET}}
      YANDEXDISK_CLIENT_ID: ${{secrets.YANDEXDISK_CLIENT_ID}}
      YANDEXDISK_CLIENT_SECRET: ${{secrets.YANDEXDISK_CLIENT_SECRET}}
      KOOFR_CLIENT_ID: ${{secrets.KOOFR_CLIENT_ID}}
      KOOFR_CLIENT_SECRET: ${{secrets.KOOFR_CLIENT_SECRET}}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout codes
        uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run build
      - name: Extract Manifest Props
        id: manifest
        run: |
          echo "tag_name=$(node -p "require('./manifest.json').version")" >> $GITHUB_ENV
          echo "plugin_id=$(node -p "require('./manifest.json').id")" >> $GITHUB_ENV
      - name: Bundle Plugin Zip
        run: |
          mkdir ${{ env.plugin_id }}
          cp main.js manifest.json styles.css ${{ env.plugin_id }}/
          zip -r ${{ env.plugin_id }}.zip ${{ env.plugin_id }}/
      - name: Create Release And Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
          name: ${{ env.tag_name }}
          files: |
            ${{ env.plugin_id }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          make_latest: true
